#!/bin/bash

clear

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║         🚨 DIAGNÓSTICO: SERVIDOR LOBECHAT CAÍDO               ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 PROBLEMA IDENTIFICADO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Servidor: chat-test.bodasdehoy.com"
echo "   Error:    500 Internal Server Error"
echo "   Impacto:  El Copilot NO funciona (iframe no carga)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 STATUS DE SERVICIOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ✅ Backend API-IA:        FUNCIONANDO"
echo "      https://api-ia.bodasdehoy.com/health → 200 OK"
echo ""
echo "   ❌ Servidor LobeChat:     CAÍDO (ERROR 500)"
echo "      https://chat-test.bodasdehoy.com/bodasdehoy/chat → 500"
echo ""
echo "   ✅ Proxy Next.js:         FUNCIONANDO"
echo "      /api/copilot/chat → OK"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 SOLUCIÓN RÁPIDA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. SSH al servidor de LobeChat"
echo "   2. Verificar logs:"
echo "      docker logs lobechat-container --tail 100"
echo ""
echo "   3. Reiniciar el servicio:"
echo "      docker-compose restart"
echo "      # o"
echo "      pm2 restart lobechat"
echo ""
echo "   4. Verificar que funcione:"
echo "      curl -I https://chat-test.bodasdehoy.com/bodasdehoy/chat"
echo "      # Debe retornar: HTTP/2 200 OK"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏱️  TIEMPO ESTIMADO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Reiniciar servidor LobeChat:     5-15 minutos"
echo "   Crear usuario en API-IA:         5 minutos"
echo "   Verificar funcionamiento:        5 minutos"
echo ""
echo "   TOTAL:                            15-25 minutos"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🐛 CAUSAS COMUNES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   • Variables de entorno faltantes (.env)"
echo "   • Base de datos PostgreSQL no accesible"
echo "   • Puerto ya en uso (EADDRINUSE)"
echo "   • Memoria insuficiente (OOM)"
echo "   • Build corrupto de Next.js"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 DOCUMENTACIÓN COMPLETA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Reporte detallado:"
echo "   scripts/REPORTE-SERVIDOR-LOBECHAT-CAIDO.md"
echo ""
echo "   Ver reporte completo:"
echo "   cat scripts/REPORTE-SERVIDOR-LOBECHAT-CAIDO.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 PRÓXIMOS PASOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   BLOQUEADOR 1 (CRÍTICO):"
echo "   → Reiniciar servidor LobeChat (ustedes lo gestionan)"
echo ""
echo "   BLOQUEADOR 2 (después de fix 1):"
echo "   → Crear usuario en BD de API-IA (ver RESUMEN-FINAL-TESTS-API-IA.md)"
echo ""
echo "   VERIFICACIÓN:"
echo "   → node scripts/test-para-proveedor.js"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║   ACCIÓN REQUERIDA: REINICIAR SERVIDOR LOBECHAT               ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
