/**
 * Re-export de tipos del paquete para uso interno de wedding-site.
 */
export type {
  WeddingSiteRendererProps,
  SectionConfig,
  ScheduleData,
  ScheduleEvent,
  LocationData,
  GalleryData,
  InfoData,
  RSVPData,
  RSVPSubmission,
  RegistryData,
  PaletteType,
  PaletteColors,
  Palette,
  ThemeProviderProps,
  SectionType,
  RenderMode,
  HeroData,
  ScheduleEventType,
  Venue,
  GalleryLayout,
  Photo,
  DressCodeType,
  DressCode,
  Accommodation,
  FAQ,
  RSVPConfig,
  RegistryLink,
  CashOption,
  WeddingWebData,
  WeddingStyle,
  CoupleInfo,
  WeddingDate,
} from '../types';
